### ISSUE TITLE
question 【the implementation of TAG-DMOEA】

### ISSUE THREAD

**Issue by walkercherish** [mssraju/TAG-DMOEA#1]
Dear Professor ,
Hello Professor, I’m sorry to disturb you in your busy schedule. I’m a student of Xi’an University of Architecture and Technology from China.
Recently, I’m learning evolutionary algorithm. Your paper A twin-archive guided decomposition based multi/many-objective evolutionary algorithm  gives me great inspiration. I admire your experiment very much, but I have encountered some troubles when trying to implement the algorithm.I downloaded the TAG-DMOEA code from github. However, there are some differences between the experimental results I obtained through platemo and the experimental results in your paper. I found that your paper is generated 𝜇 generations, before the current reference point and the distance between the reference point  to determine whether to update the weight vector. But I found in the code 𝜇 equal to 50, rather than the 𝜇 = a * MG of the paper. If possible, can you answer my question and send me the source code?
No matter whether you agree or not, best wishes to you. I would appreciate it if you could help me.
Thanks and regards.

**Comment by walkercherish** [comment]
@mssraju

**Comment by mssraju** [comment]
Dear @walkercherish 
Thank you for showing interest in our research work. Thank you for letting us know about the mistake in the code. The correct interval for regenerating weight vectors is  𝜇 only not 50 generations.

**Comment by walkercherish** [comment]
dear@mssraju, May I ask if the test result of your paper was tested by this code? The results I got from platemo were quite different.

**Comment by mssraju** [comment]
We modifies the IGD evaluation method in platemo by taking no. of reference
points = population size. That is why you are getting different results in
platemo.

**Comment by walkercherish** [comment]
dear@mssraju，i'm sorry.I'm just a student who's new to multi-objective problems. I have looked up relevant papers, but I don't quite understand no. of reference points = population size. If possible, could you please send me the modified IGD code 
or how to modify the IGD evaluation method specifically?
I would appreciate it if you could help me.
Thanks and regards.

**Comment by walkercherish** [comment]
@mssraju i'm sorry.I'm just a student who's new to multi-objective problems. I have looked up relevant papers, but I don't quite understand no. of reference points = population size. If possible, could you please send me the modified IGD code
or how to modify the IGD evaluation method specifically?
I would appreciate it if you could help me.
Thanks and regards.

**Comment by walkercherish** [comment]
Sorry, I didn't quite understand what you said before. I now understand and run results similar to those of the paper. Thank you again.
